<%@ Page Title="" Language="C#" MasterPageFile="~/App_Resources/MasterPage/AppMaster.Master" AutoEventWireup="true" CodeBehind="SubjectManagement.aspx.cs" Inherits="WebSchoolPortal.App_Resources.Pages.School_Administrator.SubjectManagement" %>

<%@ MasterType VirtualPath="~/App_Resources/MasterPage/AppMaster.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MidBodyPlacholder" runat="server">
    <link href="../../js/datatables/datatables.css" rel="stylesheet" />

    
    <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <i class="fa fa-info-sign"></i><span style="font-size:small; color:red; animation:ease-in;"><strong>Heads up!  </strong>Ensure That All The Subjects Offered In Your School Is Carefully And Correctly Inserted,Thanks........ <a href="#" class="alert-link"></a></span>

        </div>
   
    
      <section class="panel panel-default" >
        <header class="panel-heading">School Subject<i title="" data-original-title="" class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i></header>
        <div class="table-responsive">
            <div class="dataTables_wrapper no-footer" id="DataTables_Table_0_wrapper">
                <div class="row">
                    <div class="col-sm-4">
                        <asp:ValidationSummary ID="summary" runat="server" ValidationGroup="aa" />
                        <div id="DataTables_Table_0_length" class="dataTables_length">
                            <asp:TextBox placeholder="School ID" ID="SchoolId" CssClass="form-control" runat="server" ReadOnly="True" />
                            <asp:RequiredFieldValidator ID="requiredValidatorSchoolId" runat="server" ControlToValidate="SchoolId" ToolTip="School ID Required" Text="*" ValidationGroup="aa" ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="dataTables_length" id="DataTables_Table_0_filter">
                            <asp:TextBox placeholder="Subject name" ID="SubjectName"  CssClass="input-control text form-control input-lg input-group" runat="server" />
                            <asp:RequiredFieldValidator ID="requiredSubject" ControlToValidate="SubjectName" runat="server" ToolTip="Sunject Name required" Text="Please fill subject name" ValidationGroup="aa" ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div id="DataTables_Table_0length" class="dataTables_length">
                             <asp:Button runat="server" Text="Add subject" ID="RegSubject" CssClass="btn btn-success btn-block" OnClick="RegSubject_Click" ValidationGroup="aa" />
                   
                        </div>
                    </div>
                    <div style="display: none;" class="dataTables_processing" id="DataTables_Table_0_processing">Processing...</div>
                </div>
                <table aria-describedby="DataTables_Table_0_info" role="grid" id="DataTables_Table_0" class="table table-striped m-b-none dataTable no-footer" data-ride="datatables">
                    <thead>
                       
                    </thead>
                    <tbody>
                        <asp:GridView ID="SubjectGrid" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" Width="100%" CssClass=" table table-responsive table-hover " GridLines="None"  OnRowCommand="SubjectGrid_RowCommand">
                            <Columns>
                                <asp:BoundField HeaderText="Subject Name" DataField="SubjectName"  />
                                <asp:TemplateField HeaderText="Action" >
                                    <ItemTemplate >
                                        <asp:LinkButton ID="DelSub" CommandName="Del" OnClientClick="return confirm('Are you sure you want to delete record?');" CommandArgument='<%#Bind("SubjectID") %>' runat="server" class="btn btn-xs btn-primary" Text="Delete" ><i class="fa fa-cut"></i>&nbsp;Delete</asp:LinkButton>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-6">
                        <div aria-live="polite" role="status" id="DataTables_Table_0_info" class="dataTables_info"></div>
                    </div>
                    <div class="col-sm-6">
                       
                    </div>
                </div>
            </div>
        </div>
    </section>

</asp:Content>
