<%@ Page Title="" Language="C#" MasterPageFile="~/App_Resources/MasterPage/AppMaster.Master" AutoEventWireup="true" CodeBehind="StudentViewScores.aspx.cs" Inherits="WebSchoolPortal.App_Resources.Pages.Student.StudentViewScores" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MidBodyPlacholder" runat="server">
    <section class="panel panel-default">
        <div class="panel-heading">Student Assesment View</div>
        <div class="panel-body">

            <div class="table table-responsive">
             <asp:GridView ID="grvStudentScored" runat="server" AllowPaging="true" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" EmptyDataText="No recordes found" CssClass=" table table-responsive table table-hover pagination-lg"  Width="100%" GridLines="None" OnRowCommand="grvStudentScored_RowCommand" OnPageIndexChanging="grvStudentScored_PageIndexChanging">
        <Columns>
           <asp:BoundField HeaderText="Year" DataField="year" ItemStyle-ForeColor="Violet" />
            <asp:BoundField HeaderText="Class" DataField="PresentClass" />
            <asp:BoundField HeaderText="Term" DataField="Term" />
            <asp:BoundField HeaderText="Numbers of test" DataField="NumberOftest" />
            <asp:BoundField HeaderText="Numbers of exams" DataField="NumberOfExams" />
            <asp:BoundField HeaderText="Test total" DataField="TestTotal" />
            <asp:BoundField HeaderText="Exams total" DataField="ExamsTotal" />
            <asp:BoundField HeaderText="Total" DataField="total" />
            <asp:TemplateField HeaderText="View">
                <ItemTemplate>
                    <asp:LinkButton ID="lnkview" target="blank" CssClass="btn btn-sm btn-success"  Text="View" runat="server" CommandName="view" CommandArgument='<%#((GridViewRow)Container).RowIndex %>'><i class="fa fa-eye"></i></asp:LinkButton> 
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
            </div>

        </div>

    </section>
   
</asp:Content>
