<%@ Page Title="" Language="C#" MasterPageFile="~/App_Resources/MasterPage/AppMaster.Master" AutoEventWireup="true" CodeBehind="TeacherInformation.aspx.cs" Inherits="WebSchoolPortal.App_Resources.Pages.General.TeacherInformation" %>

<%@ MasterType VirtualPath="~/App_Resources/MasterPage/AppMaster.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MidBodyPlacholder" runat="server">

    <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <i class="fa fa-info-sign"></i><span style="font-size:small; color:red; animation:ease-in;"><strong>Heads up!</strong>  You Can Search For Teachers by Names,Address And Phonumber,etc... .<a href="#" class="alert-link"></a></span>

        </div>

    <section class="panel panel-default">
        <header class="panel-heading">
            <div class="input-group text-sm">
                <asp:TextBox ID="txt1" runat="server" CssClass="input-sm form-control" placeholder="Search parameters"/>
                <div class="input-group-btn">
                    <asp:linkbutton ID="Button2" type="button" runat="server"  Text="Search" class="btn btn-sm btn-default" OnClick="Button1_Click"><i class="fa fa-search"></i>&nbsp;Search</asp:linkbutton>

                </div>
            </div>
        </header>
     <div class="table-responsive">
         <div class="dataTables_wrapper no-footer" id="DataTables_Table_0_wrapper">

             <div style="display: none;" class="dataTables_processing" id="DataTables_Table_0_processing">Processing...</div>
         </div>
         <table aria-describedby="DataTables_Table_0_info" role="grid" id="DataTables_Table_0" class="table table-striped m-b-none dataTable no-footer" data-ride="datatables">
             <thead>
             </thead>
             <tbody>
                 <asp:GridView ID="TeacherGrid" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowPaging="True" PageSize="20" CssClass=" table table-responsive table-hover  " EmptyDataText="No Records Found" GridLines="None" Width="100%" >
                     <Columns>
                         <asp:BoundField HeaderText="Teacher ID" DataField="TeacherRollId"  />
                         <asp:BoundField HeaderText="Name" DataField="Name"  />
                         <asp:BoundField HeaderText="Address" DataField="ResidentialAdress" />
                         <asp:BoundField HeaderText="Phone Number" DataField="PhoneNumber" />
                         <asp:TemplateField >
                             <ItemTemplate >
                                 <asp:LinkButton Text="View" ID="viewStudent" runat="server" CommandName="Sel" CommandArgument='<%#Bind("TeacherRollId") %>' class="btn btn-xs btn-primary pull-right" ><i class="fa fa-eye"></i>&nbsp;View</asp:LinkButton>
                             </ItemTemplate>
                         </asp:TemplateField>
                     </Columns>
                 </asp:GridView>
             </tbody>
         </table>
     </div>
     
                         </section>
</asp:Content>
